name: CD

on:
  release:
    types: [published]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - name: Cached dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('yarn.lock') }}
          restore-keys: npm-

      - name: Installing dependencies
        run: yarn

      - name: Linting codebase
        run: yarn lint

      - name: Building packages
        run: yarn build

      - name: Running unit tests
        run: yarn test

      - name: Cache built packages
        uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: build-test
    strategy:
      matrix: { package: ['ga4'] }
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
          registry-url: https://registry.npmjs.org/

      - uses: actions/cache@v2
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          file-name: ./packages/${{ matrix.package }}/package.json
          file-url: https://cdn.jsdelivr.net/npm/@minimal-analytics/${{ matrix.package }}@latest/package.json
          static-checking: localIsNew

      - name: Version update detected
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Publishing package
        if: steps.check.outputs.changed == 'true'
        run: npm publish --dry-run
        working-directory: ./packages/${{ matrix.package }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
